### ISSUE TITLE
Problema al tratar de restaurar mis dotfiles

### ISSUE THREAD

**Issue by OSITO326** [CodelyTV/dotly#106]
al tratar de restaurar mis dotfiles estoy teniendo un error, segui los pasos segun los pasos segun la Issue #9 
como resultado me arroja este error: `zsh: no such file or directory: /home/osito/.dotfiles/dot`

luego segui este otro: 
## Restore your Dotfiles

* Install git
* Clone your dotfiles repository `git clone [your repository of dotfiles] $HOME/.dotfiles`
* Go to your dotfiles folder `cd $HOME/.dotfiles`
* Install git submodules `git submodule update --init --recursive`
* Install your dotfiles `DOTFILES_PATH="$HOME/.dotfiles" DOTLY_PATH="$DOTFILES_PATH/modules/dotly" "$DOTLY_PATH/bin/dot" self install`
* Restart your terminal
* Import your packages `dot package import`

En el 4to paso con el comando: `DOTFILES_PATH="$HOME/.dotfiles" DOTLY_PATH="$DOTFILES_PATH/modules/dotly" "$DOTLY_PATH/bin/dot" self install`  arroja este error: `zsh: no such file or directory: /bin/dot`

Alguien podria ayudarme por favor, gracias de antemano
P.D: SO Archlinux

**Comment by gtrabanco** [comment]
Tiene pinta de que por alguna cosa, la variable DOTLY_PATH no la pilla bien.

Prueba a ejecutar lo siguiente:

```bash
export DOTFILES_PATH="$HOME/.dotfiles" 
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"
"$DOTLY_PATH/bin/dot" self install
```
Copia y pega en consola directamente a ver que pasa.

**Comment by OSITO326** [comment]
funciono, muchas gracias! 
Cierro issue :D
