### ISSUE TITLE
zcompinit Error while installing

### ISSUE THREAD

**Issue by gtrabanco** [CodelyTV/dotly#121]
I was testing the installation with `feature/core` with a brand new user and I found this error:

```
zsh compinit: insecure directories and files, run compaudit for list.
Ignore insecure directories and files and continue [y] or abort compinit [n]? y
```

It seems like an error with ZIM?

I also test a brand new installation with master with the same problem, could anyone test just to know if is an error I only receive, please?

Anyway asnwering yes, it seems like there are no more errors... I can use it without problem.

**Comment by robertovillarejo** [comment]
También me sucede pero solo cuando abro la terminal dentro de VS Code. `compaudit` me arroja esto:

```
There are insecure directories:
/opt/homebrew/share/zsh/site-functions
/opt/homebrew/share/zsh
```

Esto fue usando la versión de `master` con el instalador tal como lo indica la documentación.

**Comment by gtrabanco** [comment]
La solución pasa por usar mi fork de este proyecto y ejecutar `dot shell fix_permissions` o ejecutar manualmente:

```bash
sudo -v
sudo chown -R "$(whoami)" /usr/local/share/zsh /usr/local/share/zsh/site-functions
chmod u+w /usr/local/share/zsh /usr/local/share/zsh/site-functions
```

**Comment by gtrabanco** [comment]
Hay una solución más sencilla, que de hecho en la propia instalación con brew de `zsh-completions` da al acabar la instalación:

```bash
chmod -R go-w '/usr/local/share/zsh'
```

Y mi solución final para el fix_permissions es esta:

```bash
    if [[ -z "${HOMEBREW_PREFIX:-}" ]] && command -v brew &>/dev/null; then
      HOMEBREW_PREFIX="$(brew --prefix)"
      chmod -R go-w "${HOMEBREW_PREFIX}/share/zsh"
    elif [[ -d "/usr/local/share/zsh" ]]; then
      HOMEBREW_PREFIX="/usr/local"
    else
      output::error "Brew not detected if you want to fix any other insecure path use \`chmod -R go-w <your_path>\`"
      exit 1
    fi

    chmod -R go-w "${HOMEBREW_PREFIX}/share/zsh"
```
