### ISSUE TITLE
Problems with installation on Mac

### ISSUE THREAD

**Issue by lmoscheni** [CodelyTV/dotly#131]
Hello everybody, I have a problem with Mac OS Big Sur, when I update the OS and restart the computer, dotly have problems running correctly and I try to remove all dotfiles and config files manually and install again, but when I run the installation command on the readme, only creates .dotfiles backup and don't do anything more.
Do you have any idea how can solve it?

Thanks for your time!

**Comment by gtrabanco** [comment]
Do you receive any error?

Can you upload  the file `~/dotly.log`?

**Comment by lmoscheni** [comment]
Sure, I run again `bash <(curl -s https://raw.githubusercontent.com/CodelyTV/dotly/master/installer)` and the output is this:
```
----- 2021-05-03 17:00:30 - Initializing repository -----
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

----- 2021-05-03 17:03:08 - Initializing repository -----
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

----- 2021-05-03 17:04:11 - Initializing repository -----
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

----- 2021-05-04 14:32:36 - Initializing repository -----
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

**Comment by lmoscheni** [comment]
I found the problem, when I update to Big Sur I had problems with Xcode dependencies I solve installing again Xcode dependencies and re-installing dotly!

Thanks for your help!
