### ISSUE TITLE
jq: orden no encontrada

### ISSUE THREAD

**Issue by Luigisa** [CodelyTV/dotly#168]
Error on execute "up" comand

i've solved the problem with this command on linux: sudo apt-get install jq

------------------

# ♻️  Updating all the apps on your system
If you want to debug what's happening behind the scenes, you can execute dot self debug in parallel.

## 🐘 Composer
Changed current directory to /home/luisg/.config/composer
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
    1/14:	http://repo.packagist.org/p/provider-archived$60d5f896e444581ddd4baae5eaf7f04b63ec618d00f1d8ddf3af1fcf41264015.json
    2/14:	http://repo.packagist.org/p/provider-2020-07$8a571317def16c1a3e82c347af8643b6c1ef47703e61fb0b4914c0424e255f51.json
    3/14:	http://repo.packagist.org/p/provider-latest$5acef179572543498650a6ec4a7e2e405019b72973e22f67b41c153904c71db5.json
    4/14:	http://repo.packagist.org/p/provider-2021-01$83a14872298465060752ee451c2d1c38473b20d5bf5da5a2ccc8d42c5f9600be.json
    5/14:	http://repo.packagist.org/p/provider-2013$d0dc77fd03e5732f1bdb80037c61df42ed94764bddb5f24774761c59739791cc.json
    6/14:	http://repo.packagist.org/p/provider-2020-10$5f45a8746e259ad1f4a913b5918b1764c7c47fae06557f26c86c9f9bdefc6e50.json
    7/14:	http://repo.packagist.org/p/provider-2016$7b8f1749c41d2c755e25992d763588fa527308b20f53fb15523c5a938d960bc4.json
    8/14:	http://repo.packagist.org/p/provider-2021-04$5589d4c48bd0b13b1c84e38b638052008022abda30a90f1104b9483dcb6e9bea.json
    9/14:	http://repo.packagist.org/p/provider-2014$ab43f689a426163c7bd97eee1359d66270cf969532a976b03d4d4e608395b25c.json
    10/14:	http://repo.packagist.org/p/provider-2019$faad80b841acda6f4b6c50e755f3aa08030d08c789c941b6f668ec28734e1956.json
    11/14:	http://repo.packagist.org/p/provider-2020$35f31d981cbcac859697f80a51b6a485ba62378c6842041a2eee6fcb0e70cdba.json
    12/14:	http://repo.packagist.org/p/provider-2015$5dd99e47c377393321c91a2b7cede7c1dff20f23728c89dd551c20543750cf5e.json
    13/14:	http://repo.packagist.org/p/provider-2017$62c94621ae4a052b1d7e00cb9398703ef09bc8f69fe8fce22e309a831b6011f9.json
    14/14:	http://repo.packagist.org/p/provider-2018$a8da54a720fed967e5abc63f2893b62641cd24b16ec9102c2417215d40e4db0d.json
    Finished: success: 14, skipped: 0, failure: 0, total: 14
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
/home/luisg/.dotfiles/modules/dotly/scripts/package/src/package_managers/composer.sh: línea 3: jq: orden no encontrada
/home/luisg/.dotfiles/modules/dotly/scripts/package/src/package_managers/composer.sh: línea 3: jq: orden no encontrada
/home/luisg/.dotfiles/modules/dotly/scripts/package/src/package_managers/composer.sh: línea 5: [: : se esperaba una expresión entera

**Comment by gtrabanco** [comment]
Check if jq is installed by executing:

```bash
which -a jq
```

Print here the output please.

@rgomezcasas

**Comment by rgomezcasas** [comment]
This should be fixed [here].(https://github.com/CodelyTV/dotly/pull/170/commits/776c9560cac433e6e07812d2ce3f8fef27eb7d9c)

Please, execute `dot self update` after [this pr](https://github.com/CodelyTV/dotly/pull/170) is merged to have the fix.

Thanks for reporting!
