### ISSUE TITLE
"ls -la" sin colores despues de instalar

### ISSUE THREAD

**Issue by Luigisa** [CodelyTV/dotly#169]
Después de hacer una instalación limpia, al hacer un "ls -la" no me salen colores de carpetas, ficheros....

**Comment by rgomezcasas** [comment]
By default dotly provides [2 aliases for that](https://github.com/CodelyTV/dotly/blob/master/dotfiles_template/shell/aliases.sh#L6), but if you want colors by default, you should modify your `$DOTFILES_PATH/shell/aliases.sh` and add the line @gtrabanco provided to you.

😊

**Comment by Luigisa** [comment]
I have checked that my alias is:
ls='command ls -G'

But I don't get any colours when I do "ls -la".

I fixed it with this directive: zmodule utility

Is this normal?

**Comment by Luigisa** [comment]
Another solution could be:
alias ls='command ls --color=yes'.
