### ISSUE TITLE
Ya no limpia mi terminal con Shortcut

### ISSUE THREAD

**Issue by ccapudev** [CodelyTV/dotly#178]
una vez instalado dotly el shortcut Ctrl + l ya no funciona,  forzadamente tengo que poner el comando clear.

**Comment by ccapudev** [comment]
El problema lo noté en Ubuntu 20.04 con bash.

**Comment by gtrabanco** [comment]
https://unix.stackexchange.com/questions/141228/control-l-not-clearing-screen/141231

**Comment by gtrabanco** [comment]
Change the `.inputrc` file to this:

```bash
$if Bash
    "\C-l": clear-screen
    "\C-b": redraw-current-line
    "\e\C-j": accept-line
    "\C-j": "\C-b\e\C-j"
    "\C-m": "\C-b\e\C-j"
$endif
```
