### ISSUE TITLE
Error al abrir nuevo terminal

### ISSUE THREAD

**Issue by lliccien** [CodelyTV/dotly#18]
Luego de instalar dotly al abrir una nueva terminal esta inicia con esto

```
/Users/usuario/.zshrc:source:10: no such file or directory: /Users/lliccien/.dotfiles/modules/dotly/modules/zimfw/init.zsh
/Users/usuario/.dotfiles/shell/init.sh:ulimit:2: setrlimit failed: invalid argument
/Users/usuario/.zlogin:source:1: no such file or directory: /Users/lliccien/.dotfiles/modules/dotly/modules/zimfw/login_init.zsh
```
SO: macOS Catalina 10.15.6
App: Iterm2

Como lo soluciono?

**Comment by Tavo5691** [comment]
Hola, el segundo error lo pude solucionar en Mac, cambiando las lineas 2 y 3 del archivo
.dotfiles/shell/init.sh por esto:

ulimit -n 10240
ulimit -u 1024

Espero te sirva.

**Comment by rgomezcasas** [comment]
I've removed the `ulimit` [part](https://github.com/CodelyTV/dotly/commit/ecbba3a5e416dcdf59059a709078a58015f96889), because this should be inside everybody personal dotfiles.

For the other error try to execute `git submodule update --recursive`

Thanks for reporting!
