### ISSUE TITLE
Add an uninstaller

### ISSUE THREAD

**Issue by lliccien** [CodelyTV/dotly#20]
Creo que es una funcionalidad básica que debe incluir @rgomezcasas

Desinstalar o volver a estado anterior

**Comment by rgomezcasas** [comment]
Hey!

Totalmente, por ahora puedes utilizar:
```bash
rm -rf dotly .dotfiles .zimrc .zshrc .zshenv .zlogin .zcompdump .zshrc.zwc .zshenv.zwc .zlogin.zwc .zcompdump.zwc
```

¡Un saludo! 😊
