### ISSUE TITLE
Los plugins no se cargan en zsh

### ISSUE THREAD

**Issue by cherrera20** [CodelyTV/dotly#202]
Buenas, 
Soy bastante nuevo con esto de zim y zsh, pero el caso es que los plugins que están en mi fichero .zimrc no se cargan:
He probado "zimfw uninstall & zimfw install" pero no hay forma.
Al hacer un zimfw list veo lo warnings como :
- ! /home/chrishj/.zimrc:5:completion: Nothing found to be initialized. Customize the module name or initialization with zmodule options.

El caso es que:
completion: /home/chrishj/.dotfiles/shell/zsh/.zim/modules/completion

la carpeta " /home/chrishj/.dotfiles/shell/zsh/.zim/modules/completion" está vacia claro. 

Me podríais echar un cable? Gracias por vuestro trabajo!!

**Comment by gtrabanco** [comment]
```
dot shell zsh optimize
dot shell zsh reload_completions
```
Y reinicia la terminal.

Ha cambiado la forma en la que se usa zimfw en el framework. Así que si esto no te funciona:

```
dot self install
```

Y luego vuelves a ejecutar los comandos del principio y reinicias la terminal.

**Comment by cherrera20** [comment]
Hola @gtrabanco gracias por tu ayuda!

He seguido los pasos que me comentas pero no ha cambiado nada.

He probado también a reinstalar antes, tal y como me aconsejas:
`dot self install`

El caso es que siguen saliendo los warnings, por ejemplo al lanzar `dot shell zsh optimize`


> ! /home/chrishj20/.zimrc:7:zsh-autosuggestions: Nothing found to be initialized. Customize the module name or initialization with zmodule options.

**Comment by cherrera20** [comment]
Añado algo de info. Si ejecuto en zsh: 
`zmodule`
Tengo el error

> zmodule: Must be called from /home/chrishj20/.zimrc

**Comment by gtrabanco** [comment]
Prueba con:

```bash
zimfw clean
zimfw compile
```

Y reinicia la terminal.

**Comment by cherrera20** [comment]
Nada. No descarga ni inicializa nada

**Comment by gtrabanco** [comment]
Haz un cat de tu `.zshrc` por fa. Si tienes algo super secreto pon unos *** o algo así.

**Comment by cherrera20** [comment]
#!/usr/bin/env zsh
# Uncomment for debuf with `zprof`
# zmodload zsh/zprof

# ZSH Ops
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FCNTL_LOCK
setopt +o nomatch
# setopt autopushd

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# Start Zim
source "$ZIM_HOME/init.zsh"

# History
HISTFILE=~/.histfile
HISTSIZE=200000
SAVEHIST=200000

# Async mode for autocompletion
ZSH_AUTOSUGGEST_USE_ASYNC=true
ZSH_HIGHLIGHT_MAXLENGTH=300

source "$DOTFILES_PATH/shell/init.sh"

fpath=("$DOTFILES_PATH/shell/zsh/themes" "$DOTFILES_PATH/shell/zsh/completions" "$DOTLY_PATH/shell/zsh/themes" "$DOTLY_PATH/shell/zsh/completions" $fpath)

autoload -Uz promptinit && promptinit
prompt ${DOTLY_THEME:-codely}

source "$DOTLY_PATH/shell/zsh/bindings/dot.zsh"
source "$DOTLY_PATH/shell/zsh/bindings/reverse_search.zsh"
source "$DOTFILES_PATH/shell/zsh/key-bindings.zsh"

**Comment by cherrera20** [comment]
De momento lo he instalado de forma manual.

Me he clonado el repo https://github.com/zsh-users/zsh-autosuggestions

y he añadido el comando:

`
source "/home/chrishj20/.dotfiles/shell/zsh/.zim/modules/zsh-autosuggestions/zsh-autosuggestions.zsh"
`

Para probar...

**Comment by gtrabanco** [comment]
```bash
zimfw list

cat "${HOME}/.zimrc"
```

**Comment by cherrera20** [comment]
Misterio resuelto
Al existir las carpetas:
/home/chrishj20/.dotfiles/shell/zsh/.zim/modules/zsh-autosuggestions
/home/chrishj20/.dotfiles/shell/zsh/.zim/modules/....
etc

el instalador daba por hecho que las tenía descargadas.!!

Muchas gracias por tu tiempo @gtrabanco
