### ISSUE TITLE
DOTLY_PATH: unbound variable

### ISSUE THREAD

**Issue by Tavo5691** [CodelyTV/dotly#21]
Luego de instalar y versionar los dotfiles en una Mac. 
Clono el repositorio a un Ubuntu, intento ejecutar:

.dotfiles/modules/dotly/bin/dot self install

Y muestra:
.dotfiles/modules/dotly/bin/dot: line 5: DOTLY_PATH: unbound variable

¿Hay algún paso que me esté faltando para poder ejecutar dot?

**Comment by rgomezcasas** [comment]
¿Podrías volver a probar?

**Comment by nabby27** [comment]
Me pasó lo mismo pero lo instalé inicialmente en Ubuntu y fui a restaurar en otro Ubuntu

**Comment by rgomezcasas** [comment]
He añadido las instrucciones aquí https://github.com/CodelyTV/dotly/commit/7b1d83145ac111e3a4e886ffc8d7f3024cc5a8e2 😊
