### ISSUE TITLE
How can I place an icon in the CODELY_THEME_STATUS_ICON_OK variable and have it displayed ?

### ISSUE THREAD

**Issue by Daespinosag** [CodelyTV/dotly#233]
I am trying to customize the theme with a png icon and have it displayed in the prom of my terminal, is this possible? how can I do it?

**Comment by rgomezcasas** [comment]
You can't with a PNG, but you can do it with a custom font. A trick is to use [nerd-fonts](https://github.com/ryanoasis/nerd-fonts#font-patcher) to path your font 🙂
