### ISSUE TITLE
dot (dotly) collides with dot (graphviz)

### ISSUE THREAD

**Issue by ticdenis** [CodelyTV/dotly#24]
Performing a couple of tests after installing dotly I realized that my installation of https://graphviz.org/ for the use of https://diagrams.mingrammer.com/ was not working properly and it was because both have the command dot.

So... would it be possible during the installation to change the dotly command for another one?
To get out of the way I renamed it to dotv for dotly.

**Comment by rgomezcasas** [comment]
Not planned for now, but what we can do to be compatibles with another `dot` binaries:
* Search all `dot` executions inside dotly and replace with the full path to it (`$DOTLY_PATH/bin/dot`)

With that you could then create an alias `dotly="$DOTLY_PATH/bin/dot"` and move the `exports.sh` preferences as you wish.

PR's are welcome 😊

**Comment by plerma** [comment]
Hey @rgomezcasas ! I was playing with `turborepo` which uses `graphviz` internally to display monorepo dependencies graph and was surprise to see the command stuck. Then I realized the command was running `dot` which is "taken" by dotly, I'm not able to follow how could I rename **dotly** `dot` command to `dott` or if I could disable it temporarily at least only meanwhile turborepo command is thrown. Any help?

**Comment by gtrabanco** [comment]
En mi fork yo he solucionado esto añadiendo lo siguiente en el loader:

```bash
function dot::undot() {
  [[ -z "${DOTLY_PATH:-}" ]] && return 1
  PATH="$(echo "$PATH" | sed -E "s|:${DOTLY_PATH:-}/bin||g")"
  printf 'export PATH="%s"' "${PATH//::/:}"
}

function dot::dotback() {
  printf 'export PATH="%s/bin:%s"' "${DOTLY_PATH:-}" "${PATH//::/:}"
}
alias undot='eval "$(dot::undot)"'
alias dotback='eval "$(dot::dotback)"'
```

![undot](https://user-images.githubusercontent.com/1969593/182364677-85f9127d-f1b2-4dd5-bee4-711b4d5a1244.gif)

**Comment by plerma** [comment]
Niceeee, that worked smoothly @gtrabanco 👏  Thanks!
