### ISSUE TITLE
Error al instalar en Ubuntu

### ISSUE THREAD

**Issue by alejandrortiz** [CodelyTV/dotly#25]
🤔 Where do you want your dotfiles to be located? (default ~/.dotfiles2): $HOME/.dotfiles
> Ok! dotfiles wll be located in: /home/marce-ldv/.dotfiles2
> Initializing your dotfiles git repository
> Cloning dotly
> Installing dotly dependencies
> Creating dotfiles structure
sed: can't read : No such file or directory

**Comment by jvegaf** [comment]
es igual que #6

**Comment by rgomezcasas** [comment]
This should be fixed with https://github.com/CodelyTV/dotly/pull/26 😊
