### ISSUE TITLE
highlighting no funciona

### ISSUE THREAD

**Issue by jdbaigorria** [CodelyTV/dotly#256]
Restaure mi configuracion de dotfiles, en realidad es tal cual como esta en este repo solo que agregue algunas carpetas de apps que uso, sin embargo me di cuenta que dejaron de funcionar los siguientes modulos:

zmodule zsh-users/zsh-syntax-highlighting
zmodule zsh-users/zsh-autosuggestions

directamente no funcionan, no se si es un tema de zim, la verdad es la primera vez que lo uso.

**Comment by GOI17** [comment]
Justo tuve este mismo problema. Segui los pasos que comenta @gtrabanco, no funciono para restaurar los plugins pero me dieron un norte con el log que me arrojo `zimfw clean` me decia que no habia nada que limpiar porque los plugins no existian. 

- Solucion
Borré `shell/zsh/.zim` y ejecute `DOTFILES_PATH="$HOME/.dotfiles" DOTLY_PATH="$DOTFILES_PATH/modules/dotly" "$DOTLY_PATH/bin/dot" self install` y ahora ya me funciona zim

**Comment by jdbaigorria** [comment]
> Justo tuve este mismo problema. Segui los pasos que comenta @gtrabanco, no funciono para restaurar los plugins pero me dieron un norte con el log que me arrojo `zimfw clean` me decia que no habia nada que limpiar porque los plugins no existian.
> 
> ### Solucion
> Borré `shell/zsh/.zim` y ejecute `DOTFILES_PATH="$HOME/.dotfiles" DOTLY_PATH="$DOTFILES_PATH/modules/dotly" "$DOTLY_PATH/bin/dot" self install` y ahora ya me funciona Zim

Hice lo mismo y funciono muchas gracias!!!!!
