### ISSUE TITLE
WSL code . no funciona

### ISSUE THREAD

**Issue by IamCocoDev** [CodelyTV/dotly#264]
Cuando intento usar code . en wsl no funciona porque usa vscode server en vez de vscode estamos usando wsl ubuntu

**Comment by GOI17** [comment]
Creo que lo que entiendo por tu problema es que si haces esto
```bash
code .
```
dentro de tu Ubuntu WSL, no abre VSCode?
En este caso, tendrias que abrir VSCode y dentro las preferencias, revisar que si este configurado el alias de `code`, en caso de que no, puedes crearlo manualmente
```bash
alias code="Visual_Studio_Code_Path"
```

**Comment by IamCocoDev** [comment]
@GOI17  muchas gracias!
