### ISSUE TITLE
Windows + WSL + DOTLY  Install Error

### ISSUE THREAD

**Issue by JoseSanchez54** [CodelyTV/dotly#265]
Hello, I'm having a problem restoring my Dotfiles repository, the first time I run Dotly everything installs fine, but when I use the restorer everything stops working, the zsh plugins don't work nor commands like nvm, bun or npm.

My repository is this https://github.com/JoseSanchez54/dotfiles

**Comment by GOI17** [comment]
Can you provide more context or the output for what is failing?
