### ISSUE TITLE
core/paths.sh cuando escribo dot devuelve illegal mode string

### ISSUE THREAD

**Issue by pazthor** [CodelyTV/dotly#28]
Cuando ejecuto el comando `dot` me responde con un _illegal mode string_,  busque las funciones y lo que hice fue remover la barra para que me funcionará.

```
{▸} ~ dot
find: -perm: /+111: illegal mode string
find: -perm: /+111: illegal mode string

✖ No executable scripts
```
No sé mucho de bash, entonces es posible que algo este omitiendo o algo haya agregado antes que provoque ese comportamiento.

agrego la linea en donde hice el cambio 
https://github.com/CodelyTV/dotly/blob/7d27bc3b0a2669c35e31ca07c63d52e02d5efb09/scripts/core/paths.sh#L4

saludos.

**Comment by pazthor** [comment]
Acabo de notar que habia un issue en Linux y lo resuelven en [17](https://github.com/CodelyTV/dotly/pull/17), seguiré revisando si algo instalé de más o me hace falta actualizar, _etc..._

**Comment by rgomezcasas** [comment]
Apuntado para revisar! :)

Gracias!!

**Comment by EduardoSimon** [comment]
En mi casó, con MAC OS Big Sur también me ocurre. He tenido que quitar el / y dejarlo como antes de la PR.

- Bash 5.0.18
- ZSH 5.8

**Comment by rgomezcasas** [comment]
Arreglado, pero de [una forma algo diferent](https://github.com/CodelyTV/dotly/commit/583995f9d93141b0b68ca238e4cb0d732bcb69ab)

Instalo los binarios de GNU para la mayoría de aplicaciones de consola
* En mac por defecto vienen versiones antiguas
* De esta manera también estos binarios tienen la misma api que en linux

Si hacéis una instalación limpia lo tendréis bien, sino podéis ejecutar esos comandos a mano y poner esos symlinks

¡Gracias!

**Comment by pazthor** [comment]
Chingon! Lo vuelvo a probar, gracias Rafa.
