### ISSUE TITLE
Cuando instalo dotly en MacOS no se instalan las dependencias de homebrew. 

### ISSUE THREAD

**Issue by MarioMH8** [CodelyTV/dotly#29]
Al instalarme dotly en MacOS he notado que no se ejecuta la parte que instala las dependencias de Homebrew.

Por lo que he podido ver en la versión del script de instalación que tenéis en el repositorio de `CodelyTV/dotfiles`, con añadir lo siguiente al final del archivo estaría resulto: 

```
if platform::is_macos; then
  output::answer "🍎 Installing MacOS custom packages"
  output::question "🌍 Network: Which name do you want to give to this computer? " "network_computer_name"
  install_macos_custom "$network_computer_name"
fi
```

Enhorabuena por el framework, me parece increíble! 🤩

**Comment by rgomezcasas** [comment]
Arreglado con lo que comentas, gracias!! 😊
