### ISSUE TITLE
Añadir visualización de la documentación de los comandos a la vista del comando dot

### ISSUE THREAD

**Issue by EduardoSimon** [CodelyTV/dotly#30]
En los dotfiles de @rgomezcasas y en el propio curso de dotfiles, se puede ver la documentación de un comando en la parte derecha del comando dot. 

![image](https://user-images.githubusercontent.com/19764148/99947240-f7ff6480-2d77-11eb-98d0-95d192ed4915.png)

He conseguido añadirlo en mi local modificando el fichero _main.sh para que lea el fichero documentation.sh:

```sh
#!/usr/bin/env bash

docs::eval() {
  eval "$(docpars -h "$(grep "^##?" "$0" | cut -c 5-)" : "$@")"
}
```

Para que funcione correctamente es necesaria la dependencia docpars. 

Abro la issue por si es una feature de la cual aceptarías PR.

Muchas gracias!

**Comment by rgomezcasas** [comment]
PR más que bienvenida! 😊

Gracias!!

**Comment by rgomezcasas** [comment]
Ya funciona todo correcto en master.
Para actualizar (hasta que añadamos un comando para ello) `cd "$DOTLY_PATH" && git pull`

😊

**Comment by EduardoSimon** [comment]
Perfecto, gracias!
