### ISSUE TITLE
Duda sobre DOTFILES_PATH  para scripts/core/_main

### ISSUE THREAD

**Issue by pazthor** [CodelyTV/dotly#35]
Para el caso de que ya se instalo dotly en el sistema (mac en mi caso), si utilizo `$git co` (o discard) me sale un error:
```
Users/juanito/.dotfiles/modules/dotly/bin/git-undo: line 5: /Users/juanito/.dotfiles/scripts/core/_main.sh: No such file or directory
```
  No seria cambiar a `DOTLY_PATH`  en lugar de `DOTFILES_PATH` para que funcione ?
  
https://github.com/CodelyTV/dotly/blob/689f51a403b8f552af7fe3cd9b201e7641c4c07c/bin/git-undo#L5

Igual creo que quizás se podria quitar de ahi, pero no se.

saludos

**Comment by rgomezcasas** [comment]
Fixeado en master!

Para actualizar (hasta que añadamos un comando para ello) haz: `cd "$DOTLY_PATH" && git pull`

Con ello ya deberías de poder utilizarlo correctamente 😊
