### ISSUE TITLE
Open folder alias not working on linux

### ISSUE THREAD

**Issue by nabby27** [CodelyTV/dotly#39]
The `open` command is a mac own command, for linux there is the `xdg-open` command.

**Comment by rgomezcasas** [comment]
Could you create an script named https://github.com/CodelyTV/dotly/tree/master/scripts/system/open that checks the SO and then executes one command or another?

Then you can change the `o.` alias to `dot system open` 😊

Thanks!

**Comment by nabby27** [comment]
@rgomezcasas I have created a folder inside `~/.dotfiles/modules/dotly/scripts` called `system` and inside a script called `open`, I have also changed the alias of `o.` for `$DOTLY_PATH/bin/dot system open` but when executing the alias or the command `dot system open` I get the error `No executable scripts`

**Comment by rgomezcasas** [comment]
Could you try:

`cd "$DOTLY_PATH" && git checkout master && git pull`

And then again?

**Comment by nabby27** [comment]
It continues not working because dotly does not detect the system folder inside scripts with the open script

**Comment by gtrabanco** [comment]
```bash
chmod u+x "$DOTFILES_PATH/scripts/system/open"
```

That happened to me, is just that you forgot to apply the execution permission to your script.

**Comment by nabby27** [comment]
I close this issue because it was a matter of permissions, thanks !!
