### ISSUE TITLE
Error: dot: can't open create

### ISSUE THREAD

**Issue by cincarnato** [CodelyTV/dotly#5]
![image](https://user-images.githubusercontent.com/7002030/81684942-d8cd6500-942d-11ea-99e4-7f07ee530c46.png)

**Comment by cincarnato** [comment]
Hola! Pudieron reproducir el problema?

Necesitan alguna información adicional?

Lo estoy intentando usar desde Ubuntu 19.

Quiero usar dotfiles!! hice el curso den codely tv

**Comment by cincarnato** [comment]
Encontré el problema!

Tenia un binario "dot" en /usr/bin/dot

Segun pude investigar este binario "dot", viene con "graphviz" que creo que se instalo por haber instalado Gimp. Esto entraba en colisión con el dot de Dotly...

Lo resolví renombrando temporalmente el binario, se les ocurre alguna solución mejor?

**Comment by jvegaf** [comment]
> Hola! Pudieron reproducir el problema?
> 
> Necesitan alguna información adicional?
> 
> Lo estoy intentando usar desde Ubuntu 19.
> 
> Quiero usar dotfiles!! hice el curso den codely tv

Puedes crearlos manualmente como indica Rafa en el curso. Dotly esta inestable todavia...

**Comment by pana1990** [comment]
Mismo error por aquí @rgomezcasas
