### ISSUE TITLE
How can we update our the dotly version used in our dotfiles?

### ISSUE THREAD

**Issue by arnau-rius** [CodelyTV/dotly#54]
I would like to update dotly to the new releases so I don't miss any new awesome feature! 😎

`dotly` is amaizing! 🙌🏼

**Comment by rgomezcasas** [comment]
If you have an older version you have to:
```bash
cd "$DOTLY_PATH"
git reset --hard
git pull origin master
dot self install
```

And that's it 😊, we'll update dotly with an `update` command ✌️

**Comment by arnau-rius** [comment]
It has worked like a charm!

**Comment by rgomezcasas** [comment]
1 year later 😂

**Comment by arnau-rius** [comment]
🤭🤣
