### ISSUE TITLE
Error instalación con wget en ubuntu 

### ISSUE THREAD

**Issue by albertsarle** [CodelyTV/dotly#6]
Hola, 

En una ubuntu 19.10 con zsh he probado de instalar mediante el comando wget, justo despues de preguntar por la carpeta  y responder con la opcion por defecto, aparece un error de que la carpeta no existe. 

Por algun motivo, en lugar de crear .dotfiles2 ha creado una carpeta que se llama asi:

'DOTFILES_PATH=DOTFILES_PATH="${DOTFILES_PATH:-$HOME'

Después de borrar esta carpeta 'estraña', he copiado el script al disco local y funciona correctamente. 

Tambien he probado el comando con bash  + curl y me ha funcionado correctamente. 

La salida del instalador es esta (sin la conexion del wget): 

wget -O - https://raw.githubusercontent.com/CodelyTV/dotly/master/installer | bash        
2020-05-14 19:30:00 (18,2 MB/s) - written to stdout [2401/2401]

  ┌────────────────────────────────────┐
~ │ 🚀 Welcome to the dotly installer! │ ~
  └────────────────────────────────────┘

 > Ok! dotfiles wll be located in: DOTFILES_PATH=DOTFILES_PATH="${DOTFILES_PATH:-$HOME/.dotfiles2}"
 > Initializing your dotfiles git repository
 > Cloning dotly
 > Installing dotly dependencies
bash: line 90: cd: DOTFILES_PATH=DOTFILES_PATH="${DOTFILES_PATH:-$HOME/.dotfiles2}"/modules/dotly: No such file or directory

**Comment by jvegaf** [comment]
En Linux Mint 20 tambien falla con wget y con curl

➜  ~ bash <(curl -s https://raw.githubusercontent.com/CodelyTV/dotly/master/installer)

  ┌────────────────────────────────────┐
~ │ 🚀 Welcome to the dotly installer! │ ~
  └────────────────────────────────────┘

🤔 Where do you want your dotfiles to be located? (default ~/.dotfiles2): 
 > Ok! dotfiles wll be located in: /home/jose/.dotfiles2
 > Initializing your dotfiles git repository
 > Cloning dotly
 > Installing dotly dependencies
 > Creating dotfiles structure
sed: can't read : No such file or directory

**Comment by pana1990** [comment]
Me pasa el mismo error que @jvegaf

**Comment by rgomezcasas** [comment]
There were 2 errors here:
1. The correct command to execute this using `wget` is: `bash <(wget -qO- https://raw.githubusercontent.com/CodelyTV/dotly/master/installer)`
    * The error was that with the old command we can't run interactive commands, and this is interactive
    * Readme updated https://github.com/CodelyTV/dotly/commit/039209079ddddc3e7f4fdf867f1ea9ed7924b9df
2. There were a `sed` error installing on Linux-based OSs
    * Fixed in #26 
        - Also in this PR I added some `CI`, so we can be sure we won't brake anything in the future 😳
