### ISSUE TITLE
Error búsquedas con find (macos)

### ISSUE THREAD

**Issue by josepgarcia** [CodelyTV/dotly#60]
Ejemplo:
```
cd ~/.dotfiles
```

Búsqueda correcta
```
find . -name install
./modules/dotly/scripts/self/install
./modules/dotly/scripts/package/install
./modules/dotly/modules/dotbot/tools/git-submodule/install
./modules/dotly/modules/dotbot/tools/hg-subrepo/install
```

Error en la búsqueda al utilizar *
```
find . -name inst*
zsh: no matches found: inst*
```

Posible solución, añadir a .dotfiles/./shell/init.sh
```
setopt +o nomatch
```

**Comment by josepgarcia** [comment]
No funciona la búsqueda de archivos utilizando el comando find con asterisco (ver ejemplo).

**Comment by gtrabanco** [comment]
When gives you that error?

**Comment by josepgarcia** [comment]
When I install dotly on a user can not use * in find command.

Example, new user and new install of dotly (I do the tests in the dotfiles folder):
```
{▸} ~/.dotfiles on master $   pwd
/Users/ana/.dotfiles
```

I can find without *:
```
{▸} ~/.dotfiles on master $  find . -name install
./modules/dotly/scripts/self/install
./modules/dotly/scripts/package/install
./modules/dotly/modules/dotbot/tools/git-submodule/install
./modules/dotly/modules/dotbot/tools/hg-subrepo/install
```

But I get an error if I use *, (same directory):
```
{▸} ~/.dotfiles on master $ find . -name insta*
zsh: no matches found: insta*

```

If I run
```
$ setopt +o nomatch
```

Find works fine (same directory)
```
{▸} ~/.dotfiles on master $ find . -name insta*
./modules/dotly/scripts/self/install
./modules/dotly/scripts/self/utils/install.sh
./modules/dotly/scripts/package/install
./modules/dotly/modules/dotbot/tools/git-submodule/install
./modules/dotly/modules/dotbot/tools/hg-subrepo/install
./modules/dotly/modules/zimfw/modules/zsh-autosuggestions/install_test_zsh.sh
./modules/dotly/modules/zimfw/src/tools/install.zsh.erb
./modules/dotly/installer
```

**Comment by gtrabanco** [comment]
Do you have installed NVM? https://github.com/nvm-sh/nvm/issues/1937

I did not found any information about zimfw having smae option and I did not found any modification in dotly files.

Not sure if it is a zsh default option but I do not think so...

**Comment by rgomezcasas** [comment]
It's like @gtrabanco says, it's the default behaviour for `zsh`, but since it's quite interesting I've added that opt here https://github.com/CodelyTV/dotly/commit/bca5703067391aa4fee91d3cd7e70c9c432ba8bc

Every new default installation will have it enabled by default.

**Comment by gtrabanco** [comment]
@rgomezcasas Sorry, I dot not want to sound rough, it's just a question.

Are you sure that framework should modify expected working (which is the default behaviour)?
