### ISSUE TITLE
error al ejecutar dot en ubuntu

### ISSUE THREAD

**Issue by cincarnato** [CodelyTV/dotly#8]
Al ejecutar dot en ubuntu obtengo el siguiente error:

**find: modo inválido ‘+111’**

Modifique el find que hace dot por **"-perm /111"** en vez de "-perm +111" y ahora funciona

Me guié de las opciones de esta gua: https://www.ostechnix.com/find-files-based-permissions/

Igualmente entiendo que si estos scripts, están dentro de mi dotfiles, mas que seguro tienen que tener permisos para mi usuario, no?

**Comment by sanchezcarlosjr** [comment]
Old line 12
```bash
list_command_paths() {
    find "$DOTFILES_PATH/scripts" -maxdepth 2 -perm +111 -type f |
    grep -v core |
    sort
}
```

New Line 12
```bash
list_command_paths() {
  find "$DOTFILES_PATH/scripts" -maxdepth 2 -perm /111 -type f |
    grep -v core |
    sort
}
```

**Comment by rgomezcasas** [comment]
This should be fixed with #17 😊

Thanks for reporting!!
