### ISSUE TITLE
Cargo update problem

### ISSUE THREAD

**Issue by gtrabanco** [CodelyTV/dotly#83]
When executing `cargo update` I am having this error:

```
error: could not find `Cargo.toml` in `/Users/<username>` or any parent directory
```

MacOS Big Sur 11.2

This affects to `dot package update_all` do not know why I am getting this error. I tried:
- Creating the file manually empty after uninstalling all packages and reinstalling them.
- Uninstall rust and reinstall.
- Updated Command Line Tools

No valid solution found. I know it is not a dotly error, but could affects to one command of dotly.

**Comment by rgomezcasas** [comment]
This was also affecting me 😅 

We're "manually" updating every `cargo` package now 😊

**Comment by gtrabanco** [comment]
It's also not working only for one package:

```bash
cargo update --package docpars
error: could not find `Cargo.toml` in `/Users/gtrabanco` or any parent directory
```

How do you update each package? Uninstalling and installing it?
