### ISSUE TITLE
Error Installing on WSL

### ISSUE THREAD

**Issue by asignes86** [CodelyTV/dotly#91]
I get this error installing on Win10 with WSL Ubuntu 	

Intalling rust
`error: linker `cc` not found`

I solved following this post
[solution](https://ostechnix.com/how-to-fix-rust-error-linker-cc-not-found-on-linux/)

**Comment by asignes86** [comment]
tracelog of error
` > rust not installed, installing
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-12-31, rust version 1.49.0 (e1884a8e3 2020-12-29)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'
 > docpars not installed, installing
        error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: could not compile `memchr`

To learn more, run the command again with --verbose.
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: failed to compile `docpars v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-installAueyDf`

Caused by:
  build failed`

**Comment by rgomezcasas** [comment]
Do you feel confortable creating a pull request adding that dependency on linux? 😊

**Comment by asignes86** [comment]
challenge accepted 😝
