### ISSUE TITLE
Autocompletions error while entering bash mode

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/dotly#93]
# How to reproduce

- Install dotly
- Restart your Terminal
- Execute `bash`

# Output

```
{▸} ~ bash                                                                             
bash: /Users/javiercane/.dotfiles/shell/bash/completions/*: No such file or directory
```

# Expected

No errors in the output

# Workaround

```bash
rm ~/.dotfiles/shell/bash/completions/.gitkeep
```

**Comment by gtrabanco** [comment]
Pending approval of PR #95 that tries to solve this issue.

Thanks a lot @JavierCane

**Comment by gtrabanco** [comment]
This was fixed so this issue can be closed.
